server:
  port: 8080

spring:
  application:
    name: Springboot_SpringSecurity_JWT

  config:
    import: optional:file:../../../.env

  datasource:
    url: jdbc:mariadb://localhost:3306/jwt_db?useSSL=false&allowPublicKeyRetrieval=true&useServerPrepStmts=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  issuer: jjjooo
  secret:
    access: ${JWT_ACCESS_SECRET}
    refresh: ${JWT_REFRESH_SECRET}
